const DEFAULT_METHOD = "single";
const DEFAULT_TARGET_LANG = "ru";
const DEFAULT_SOURCE_LANG = "auto";
const DEFAULT_CHUNK_SIZE_LIMIT = 4000;

const DELIMITER_TOKEN = "__BG3_TRANSLATOR_SEGMENT_9f2b4e__";
const DELIMITER = `\n${DELIMITER_TOKEN}\n`;

const MARKUP_OR_PLACEHOLDER_SPLIT_REGEX = /(<\/?[A-Za-z][^>]*>|\[\d+\])/g;
const MARKUP_TOKEN_REGEX = /^<\/?[A-Za-z][^>]*>$/;
const PLACEHOLDER_TOKEN_REGEX = /^\[\d+\]$/;

module.exports = {
  DEFAULT_METHOD,
  DEFAULT_TARGET_LANG,
  DEFAULT_SOURCE_LANG,
  DEFAULT_CHUNK_SIZE_LIMIT,
  DELIMITER_TOKEN,
  DELIMITER,
  MARKUP_OR_PLACEHOLDER_SPLIT_REGEX,
  MARKUP_TOKEN_REGEX,
  PLACEHOLDER_TOKEN_REGEX,
};
