export const AI_SETTINGS_STRINGS = {
  alertTitle: 'Нужны настройки AI',
  alertBody: 'Для запуска нейросети укажите API ключ для выбранной модели.',
  settingsTitle: 'Настройки приложения',
  settingsSubtitle: 'Конфигурация нейросетей',
  githubKeyLabel: 'API Ключ GitHub (Для моделей GPT)',
  openRouterKeyLabel: 'API Ключ OpenRouter (Для Auto-Routing)',
  modelLabel: 'Модель перевода',
  modelHint: 'Вы можете в любой момент менять модель, если у вас прописаны для нее ключи.',
  modelFallbackHint: 'Введите хотя бы один ключ API для начала работы.',
  closeButton: 'Закрыть',
  settingsButton: 'В настройки',
  cancelButton: 'Отмена',
  saveButton: 'Сохранить',
};